backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Portfolio"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Bio", name: "body", widget: "markdown" }